name: RedSorcery
version: '${version}'
main: io.github.sarahgreywolf.redsorcery.RedSorcery
api-version: 1.19
load: STARTUP
author: sarahgreywolf
description: Minecraft Paper plugin that adds rituals to interact with the world aswell as players and their tools.
website:
commands:
  RedSorcery:
    description: Base command for RedSorcery
    usage: /redsorcery
    default: true
